In [1]:
import tkinter as tk
from tkinter import ttk
from tkinter import *
import sqlite3

from tkinter import messagebox



def Database():
    fnm=fname1.get()
    lnm=lname.get()
    d=date.get()
    m=month.get()
    y=year.get()
    em=email.get()
    mob=mobn.get()
    
    db = sqlite3.connect('stform.db')
    cursor=db.cursor()
    cursor.execute('CREATE TABLE IF NOT EXISTS STFORM(fname TEXT,lname TEXT,date INT,month TEXT,year INT,email TEXT,mobn INT)')
    cursor.execute('INSERT INTO STFORM(fname,lname,date,month,year,email,mobn) VALUES(?,?,?,?,?,?,?)',
                   (fnm,lnm,d,m,y,em,mob))
    db.commit()
    msg = messagebox.showinfo( "DB Demo","SUBMITTED SUCCESSFULLY")
    
    
def display():
    db = sqlite3.connect('stform.db')
    with db:
      cursor=db.cursor()
      window = ttk.Tk()
      window.geometry("400x250") 

    select=cursor.execute('''SELECT * from STFORM1 ''');
    i=0  
    for STFORM in select: 
            for j in range(len(STFORM)):
                e = Entry(my_w, width=10, fg='blue') 
                e.grid(row=i, column=j) 
                e.insert(END, STFORM[j])
            i=i+1  


an = Tk()
an.geometry("1100x900")

an.title("SET 1 - DINESH REDDY RA1911028010098" )
an.configure(background="Purple")

stud = Label(an,text="STUDENT REGISTRATION FORM",font=("Calibri Bold",24),foreground="Black").place(x=380,y=0)

fname= Label(an,text="FIRST NAME:- ",font=("Calibri",12)).place(x=100,y=60)
fname1= Entry(an,width=40)
fname1.place(x=250,y=63)
maxc = Label(an,text="(Max 30 charcters only a-z or A-Z)",font=("Calibri",8)).place(x=500,y=63)

lname = Label(an,text="LAST NAME:- ",font=("Calibri",12)).place(x=100,y=90)
lname = Entry(an,width=40)
lname.place(x=250,y=93)

maxn = Label(an,text="(Max 30 charcters only a-z or A-Z)",font=("Calibri",8)).place(x=500,y=93)

dob = Label(an,text="DATE OF BIRTH:-",font=("Calibri",12)).place(x=100,y=120)
date = ttk.Combobox(an,text="Date",width=5)
date['values']=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31)
date.place(x=250,y=123)

month = ttk.Combobox(an,text="Month",width=10)
month['values']=("JAN(1)","FEB(2)","MAR(3)","APR(4)","MAY(5)","JUN(6)","JUL(7)","AUG(8)","SEP(9)","OCT(10)","NOV(11)","DEC(12)")
month.place(x=310,y=123)

year = ttk.Combobox(an,text="Month",width=10)
year['values']=(1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005)
year.place(x=400,y=123)

email = Label(an,text="EMAIL ID:- ",font=("Calibri",12)).place(x=100,y=150)
email = Entry(an,width=40)
email.place(x=250,y=153)

mobn = Label(an,text="MOBILE NUMBER:- ",font=("Calibri",12)).place(x=100,y=180)
mobn = Entry(an,width=20)
mobn.place(x=250,y=183)
maxd = Label(an,text="(Max 10 numbers only 0-10)",font=("Calibri",8)).place(x=380,y=183)

gender = Label(an,text="GENDER:- ",font=("Calibri",12)).place(x=100,y=210)
male = ttk.Radiobutton(an,text="MALE",value=1)
male.place(x=250,y=212)
female=ttk.Radiobutton(an,text="FEMALE",value=2)
female.place(x=320,y=212)

address = Label(an,text="ADDRESS:- ",font=("Calibri",12)).place(x=100,y=240)
address = Entry(an,width=40)
address.place(x=250,y=243)

ad1 = Entry(an,width=40)
ad1.place(x=250,y=273)

city = Label(an,text="CITY:- ",font=("Calibri",12)).place(x=100,y=300)
city = Entry(an,width=30)
city.place(x=250,y=303)

pin = Label(an,text="PINCODE:- ",font=("Calibri",12)).place(x=100,y=330)
pin = Entry(an,width=30)
pin.place(x=250,y=333)

state = Label(an,text="STATE:- ",font=("Calibri",12)).place(x=100,y=360)
state = Entry(an,width=30)
state.place(x=250,y=363)

country = Label(an,text="COUNTRY:- ",font=("Calibri",12)).place(x=100,y=390)
country = Entry(an,width=30)
country.place(x=250,y=393)

hobby = Label(an,text="HOBBIES:- ",font=("Calibri",12)).place(x=100,y=420)
hobby = ttk.Combobox(an,text="Month",width=29)
hobby['values']=("DRAWING ","SKETCHING ","DANCING ")
hobby.place(x=250,y=420)
oth =Label(an,text="OTHER ").place(x=250,y=450)
other = Entry(an,width=20)
other.place(x=320,y=453)

qua = Label(an,text="QUALIFICATION:- ",font=("Calibri",12)).place(x=100,y=480)
si = Label(an,text="SI.NO ",font=("Calibri",12)).place(x=250,y=480)
exam=Label(an,text="EXAMINATION",font=("Calibri",12)).place(x=330,y=480)
board=Label(an,text="BOARD",font=("Calibri",12)).place(x=500,y=480)
per = Label(an,text="PERCENTAGE",font=("Calibri",12)).place(x=615,y=480)
yop = Label(an,text="YEAR OF PASSING",font=("Calibri",12)).place(x=737,y=480)
one = Label(an,text="1",font=("Calibri",12)).place(x=260,y=510)
sec = Label(an,text="2",font=("Calibri",12)).place(x=260,y=540)
trd = Label(an,text="3",font=("Calibri",12)).place(x=260,y=570)
four= Label(an,text="4",font=("Calibri",12)).place(x=260,y=600)

ten = Label(an,text="CLASS X",font=("Calibri",12)).place(x=340,y=510)
twe = Label(an,text="CLASS XII",font=("Calibri",12)).place(x=340,y=540)
grad= Label(an,text="GRADUATION",font=("Calibri",12)).place(x=340,y=570)
mast= Label(an,text="MASTERS",font=("Calibri",12)).place(x=340,y=600)

tenmax = Label(an,text="(10 Char max)",font=("Calibri",8)).place(x=495,y=620)
dec = Label(an,text="(Upto 2 Decimal)",font=("Calibri",8)).place(x=625,y=620)

b1 = Entry(an,width=20)
b1.place(x=465,y=510)
b2 = Entry(an,width=20)
b2.place(x=465,y=540)
b3 = Entry(an,width=20)
b3.place(x=465,y=570)
b4 = Entry(an,width=20)
b4.place(x=465,y=600)

p1 = Entry(an,width=20)
p1.place(x=600,y=510)
p2 = Entry(an,width=20)
p2.place(x=600,y=540)
p3 = Entry(an,width=20)
p3.place(x=600,y=570)
p4 = Entry(an,width=20)
p4.place(x=600,y=600)

y1 = Entry(an,width=20)
y1.place(x=735,y=510)
y2 = Entry(an,width=20)
y2.place(x=735,y=540)
y3 = Entry(an,width=20)
y3.place(x=735,y=570)
y4 = Entry(an,width=20)
y4.place(x=735,y=600)

caf = Label(an,text="APPLY COURSE:- ",font=("Calibri",12)).place(x=100,y=660)

bca = ttk.Radiobutton(an,text="BCA ").place(x=250,y=663)
bcom= ttk.Radiobutton(an,text="B.COM ").place(x=320,y=663)
bsc = ttk.Radiobutton(an,text="Bsc ").place(x=400,y=663)
ba =  ttk.Radiobutton(an,text="BA ").place(x=470,y=663)

msg=Button(an, text='SUBMIT',width=20).place(x=400,y=730)
msg=Button(an,text="DISPLAY RECORD(s)",width=20,command=Database).place(x=600,y=730) 

an.mainloop()

In [2]:
import sqlite3
my_conn = sqlite3.connect('stform.db')

import tkinter  as tk 
from tkinter import * 
window = tk.Tk()
window.geometry("700x250") 

select=my_conn.execute('''SELECT * from STFORM ''');
i=0 # row value inside the loop 
for STFORM in select: 
    for j in range(len(STFORM)):
        e = Entry(window, width=10, fg='black') 
        e.grid(row=i, column=j) 
        e.insert(END, STFORM[j])
    i=i+1
window.mainloop()